### ISSUE TITLE
`debitFees()` and `creditFees()` non-atomicity when surpassing intrinsic gas limits.

### ISSUE THREAD

**Issue by ezdac** [celo-org/op-geth#177] opened 2024-07-18 09:25 UTC
Currently we deduct an additional global, constant intrinsic gas for fee currency transactions
and we want to change that to querying this value per currency from the `FeeCurrencyDirectory` (#125).

Within the STF we allow the calls to `debitFees` and `creditFees` combined to only use `const * intrinsic-currency-gas`,
otherwise the call to the contract fails with an out-of-gas.

Within the transaction-pool, we only simulate a `debitFees` call as part of the transaction validity check. If that does not fail with an out-of-gas when `x * intrinsic-currency-gas` is supplied, we consider the transaction valid and it will get included in the block.
Now it could happen that only the `creditFees` uses a very high amount of gas during transaction execution.
This would:
- leave the fees debited
- potentially apply the user's transaction to the state
- **not** credit a gas refund to the user and distribute the inclusion fees to validators etc.

It is not necessarily the user's fault that that happens, since either the currency contract has an untested execution path with a high gas usage, or the intrinsic-gas limit was set too low on the `FeeCurrencyDirectory`.

@karlb  and I argued that the outcome to the state as described above is fine as is and it's better than 
letting the whole transaction fail atomically.

We could also additionally simulate the `creditFees` function in the tx-pool validation, however this is computationally expensive.
Additionally since the input-parameters (gas refund amount, gas used) depend on the outcome of the user's transaction, the function would have to be simulated with different parameters than in the STF, or the **full** state-transition including the user's transaction would have to be simulated in the transaction-pool, which would introduce a massive DoS vector.

*If we decide it is okay that the `creditFees` call can fail, this has an impact on fee-currency contract guarantees.
Most importantly, the contract should not rely on assuming that `creditedTotalAmount == debitedTotalAmount`.*

There currently is a bug in the STF code, leading to the case where the state reflects the changes described above (applied debit + transaction), but the transaction was not marked as "successful", and thus could not be retrieved by the transaction receipt endpoint.

https://github.com/celo-org/op-geth/blob/dd7c8496993c32faa0afd3839c05647100c1e863/core/state_transition.go#L668-L670

**Comment by mcortesi** [comment] 2024-07-18 09:35
Some relevant notion docs on this problem, since it has been analyzed before:

* https://www.notion.so/clabsco/Intrinsic-gas-for-CEL2-fee-currencies-919f3a76d1824fb9ac8f1031058d3f07?pvs=4
* https://www.notion.so/clabsco/ERC20-fee-currencies-for-CEL2-7fbf7c53e52c4cacab6e8e61d290fe93?pvs=4

Now, talking from memory... the issue is:

**If Credit Fails, due to Out of Gas. What do we do?**

A think the option we ended choosing was:

Don't let it fail => provide a GAS amount much bigger than intrinsic gas or at least `k * intrinsicGas` where `k > 1`. 

     * If this fails then it's a very odd case. We can revert the tx
     * If this work but consumes more than `intrinsicGas`, then record that and have a protocol to increase the intrinsicGas. I believe such a protocol was described some where in the documents. (@carterqw2 do you remember where?)

**Comment by mcortesi** [comment] 2024-07-18 09:54
My 2cents...

We have to revert if `creditFee` fails. Since if we don't fail, we're breaking our contract with ERC20 fee currencies. Those that implement the protocol EXPECT that for each DEBIT there's a CREDIT.

If we have a DEBIT but not the CREDIT (due to revert), the contract state might break.

@pahor167 might have actual examples of this

**Comment by ezdac** [comment] 2024-07-18 10:02
To me this just feels a little bit odd, since normally the gas conditions are part of the transaction validity and transactions that could theoretically pay the fees are included in a block, and others are rejected from the tx-pool.
This would not be exactly like that in this case.

And the problem is to prevent DoS we *have to* subtract the gas that was used for computation either way.
So as soon as a transaction is included in the block and the tx code executed, we have to be certain that the user **has** to pay for that computation and the gas deducted.

**Comment by karlb** [comment] 2024-07-19 11:02
> Don't let it fail => provide a GAS amount much bigger than intrinsic gas or at least k * intrinsicGas where k > 1.

We currently allow up to `3 * intrinsicGas` for the debit+credit execution. If the combined gas cost is between `intrinsicGas` and `3 * intrinsicGas` we create a log message to make the problem visible, but proceed to with the tx execution as normal. We only have a problem when the gas currency exceeds `3 * intrinsicGas`, which will cause the credit to fail. This issue is only about this unusual case. I consider that case a misconfiguration of the respective fee currency (either such a high gas cost should be impossible or the `intrinsicGas` value must be increased). We should still handle it gracefully.

>  If this fails then it's a very odd case. We can revert the tx

This would be a DoS vector, since a tx sender could cause a considerable amount of computation without paying anything for it. This can be mitigated by
* Keeping the fee currency specific block gas limit low enough
* Quickly updating the `intrinsicGas` for the fee currency (hard to do quickly, since it involved a governance proposal)

Are these good enough for such an unusual case? Any other ways to reduce the risk?

> If this work but consumes more than `intrinsicGas`, then record that and have a protocol to increase the intrinsicGas. I believe such a protocol was described some where in the documents. (@carterqw2 do you remember where?)

It was mentioned and chosen as the desired solution here: https://www.notion.so/clabsco/Intrinsic-gas-for-CEL2-fee-currencies-919f3a76d1824fb9ac8f1031058d3f07?pvs=4#d9b72ad7af5a4109913443688563a6f8

Since we can't measure the exact gas requirement in this case, we could just increase the intrinsic gas by a factor of three. That would only become effective in the next block, so we must not waste so many resources in the error case that we can't finish the block.

> If we have a DEBIT but not the CREDIT (due to revert), the contract state might break.

Yes, I've seen code from one fee currency where missing a credit would break all future uses of that token as fee currency.

**Comment by karlb** [comment] 2024-07-23 12:39
After talking with @mcortesi, we agreed that it would best if we revert txs where the credit fails (revert all of debit + tx + credit) and try to limit the impact of DoS attacks for that case to a DoS of only that specific fee currency.

This could be done by setting the fee currency specific block gas limit to zero or by keeping a separate fee currency blacklist with entries that expire after a while. The specifics can be chosen to keep the implementation simple. If a blacklist only applies to the local node, that is acceptable.

`creditGasFees` reverts could happen for reasons other than running out of gas, so handling all reverts with the same mechanism would be great.

**Comment by mcortesi** [comment] 2024-09-18 17:34
@karlb should we then close this?

**Comment by ezdac** [comment] 2024-09-19 07:51
@mcortesi there is a PR being reviewed right now that will implement the proposed changes and auto-close this issue soon.

Or were there any new out-of-band decisions regarding this not tracked in this issue discussion?

**Closed as completed** 2024-09-19 13:34 UTC
Labels: type:bug
